/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AplrTrainingRouteImport } from './routes/aplr-training'
import { Route as BasicMathTrainingRouteImport } from './routes/basic-math-training'
import { Route as CandidateAuthRouteImport } from './routes/candidate-auth'
import { Route as CandidateProfileRouteImport } from './routes/candidate-profile'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClientChatRouteImport } from './routes/client-chat'
import { Route as ClientOnboardingRouteImport } from './routes/client-onboarding'
import { Route as ClientProfileRouteImport } from './routes/client-profile'
import { Route as CommunicationTrainingRouteImport } from './routes/communication-training'
import { Route as CommunicationTrainingHistoryRouteImport } from './routes/communication-training-history'
import { Route as CommunicationTrainingTipsRouteImport } from './routes/communication-training-tips'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CompanyDrivesRouteImport } from './routes/company-drives'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DailyTargetsRouteImport } from './routes/daily-targets'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DrivesRouteImport } from './routes/drives'
import { Route as DsaTrainingRouteImport } from './routes/dsa-training'
import { Route as EnglishTrainingRouteImport } from './routes/english-training'
import { Route as EnglishTrainingHistoryRouteImport } from './routes/english-training-history'
import { Route as EnglishTrainingTipsRouteImport } from './routes/english-training-tips'
import { Route as GdHistoryRouteImport } from './routes/gd-history'
import { Route as GdRoomRouteImport } from './routes/gd-room'
import { Route as GdTrainingRouteImport } from './routes/gd-training'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as InstituteBillingRouteImport } from './routes/institute-billing'
import { Route as InstitutionAuthRouteImport } from './routes/institution-auth'
import { Route as LdTrainingRouteImport } from './routes/ld-training'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as MockInterviewRouteImport } from './routes/mock-interview'
import { Route as MockInterviewHistoryRouteImport } from './routes/mock-interview-history'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlacementCellRouteImport } from './routes/placement-cell'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as RoadmapDrillRouteImport } from './routes/roadmap-drill'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as SelfTrainingRouteImport } from './routes/self-training'
import { Route as SituationalTrainingRouteImport } from './routes/situational-training'
import { Route as StudentMessageRouteImport } from './routes/student-message'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as TacRouteImport } from './routes/tac'
import { Route as TechnicalTrainingRouteImport } from './routes/technical-training'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as CommunicationTrainingReportSessionIdRouteImport } from './routes/communication-training-report.$sessionId'
import { Route as CompanyDrivesCompanyIdRouteImport } from './routes/company-drives_.$companyId'
import { Route as EnglishTrainingReportSessionIdRouteImport } from './routes/english-training-report.$sessionId'
import { Route as GdReportGdIdRouteImport } from './routes/gd-report.$gdId'
import { Route as InterviewAnalysisInterviewIdRouteImport } from './routes/interview-analysis.$interviewId'
import { Route as MockInterviewTranscriptInterviewIdRouteImport } from './routes/mock-interview-transcript.$interviewId'
import { Route as StudentActivityStudentIdRouteImport } from './routes/student-activity.$studentId'
import { Route as StudentDataStudentIdRouteImport } from './routes/student-data.$studentId'
import { Route as StudentDetailStudentIdRouteImport } from './routes/student-detail.$studentId'
import { Route as StudentInterviewEvidenceStudentIdInterviewIdRouteImport } from './routes/student-interview-evidence.$studentId.$interviewId'
import { Route as StudentModuleStudentIdModuleKeyRouteImport } from './routes/student-module.$studentId.$moduleKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AplrTrainingRoute = AplrTrainingRouteImport.update({
  id: '/aplr-training',
  path: '/aplr-training',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicMathTrainingRoute = BasicMathTrainingRouteImport.update({
  id: '/basic-math-training',
  path: '/basic-math-training',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAuthRoute = CandidateAuthRouteImport.update({
  id: '/candidate-auth',
  path: '/candidate-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate-profile',
  path: '/candidate-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientChatRoute = ClientChatRouteImport.update({
  id: '/client-chat',
  path: '/client-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientOnboardingRoute = ClientOnboardingRouteImport.update({
  id: '/client-onboarding',
  path: '/client-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/client-profile',
  path: '/client-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationTrainingRoute = CommunicationTrainingRouteImport.update({
  id: '/communication-training',
  path: '/communication-training',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationTrainingHistoryRoute =
  CommunicationTrainingHistoryRouteImport.update({
    id: '/communication-training-history',
    path: '/communication-training-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunicationTrainingTipsRoute =
  CommunicationTrainingTipsRouteImport.update({
    id: '/communication-training-tips',
    path: '/communication-training-tips',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDrivesRoute = CompanyDrivesRouteImport.update({
  id: '/company-drives',
  path: '/company-drives',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyTargetsRoute = DailyTargetsRouteImport.update({
  id: '/daily-targets',
  path: '/daily-targets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivesRoute = DrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaTrainingRoute = DsaTrainingRouteImport.update({
  id: '/dsa-training',
  path: '/dsa-training',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishTrainingRoute = EnglishTrainingRouteImport.update({
  id: '/english-training',
  path: '/english-training',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishTrainingHistoryRoute = EnglishTrainingHistoryRouteImport.update({
  id: '/english-training-history',
  path: '/english-training-history',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishTrainingTipsRoute = EnglishTrainingTipsRouteImport.update({
  id: '/english-training-tips',
  path: '/english-training-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const GdHistoryRoute = GdHistoryRouteImport.update({
  id: '/gd-history',
  path: '/gd-history',
  getParentRoute: () => rootRouteImport,
} as any)
const GdRoomRoute = GdRoomRouteImport.update({
  id: '/gd-room',
  path: '/gd-room',
  getParentRoute: () => rootRouteImport,
} as any)
const GdTrainingRoute = GdTrainingRouteImport.update({
  id: '/gd-training',
  path: '/gd-training',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteBillingRoute = InstituteBillingRouteImport.update({
  id: '/institute-billing',
  path: '/institute-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionAuthRoute = InstitutionAuthRouteImport.update({
  id: '/institution-auth',
  path: '/institution-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LdTrainingRoute = LdTrainingRouteImport.update({
  id: '/ld-training',
  path: '/ld-training',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const MockInterviewRoute = MockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const MockInterviewHistoryRoute = MockInterviewHistoryRouteImport.update({
  id: '/mock-interview-history',
  path: '/mock-interview-history',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementCellRoute = PlacementCellRouteImport.update({
  id: '/placement-cell',
  path: '/placement-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapDrillRoute = RoadmapDrillRouteImport.update({
  id: '/roadmap-drill',
  path: '/roadmap-drill',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfTrainingRoute = SelfTrainingRouteImport.update({
  id: '/self-training',
  path: '/self-training',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationalTrainingRoute = SituationalTrainingRouteImport.update({
  id: '/situational-training',
  path: '/situational-training',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMessageRoute = StudentMessageRouteImport.update({
  id: '/student-message',
  path: '/student-message',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TacRoute = TacRouteImport.update({
  id: '/tac',
  path: '/tac',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalTrainingRoute = TechnicalTrainingRouteImport.update({
  id: '/technical-training',
  path: '/technical-training',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationTrainingReportSessionIdRoute =
  CommunicationTrainingReportSessionIdRouteImport.update({
    id: '/communication-training-report/$sessionId',
    path: '/communication-training-report/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyDrivesCompanyIdRoute = CompanyDrivesCompanyIdRouteImport.update({
  id: '/company-drives_/$companyId',
  path: '/company-drives/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishTrainingReportSessionIdRoute =
  EnglishTrainingReportSessionIdRouteImport.update({
    id: '/english-training-report/$sessionId',
    path: '/english-training-report/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GdReportGdIdRoute = GdReportGdIdRouteImport.update({
  id: '/gd-report/$gdId',
  path: '/gd-report/$gdId',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewAnalysisInterviewIdRoute =
  InterviewAnalysisInterviewIdRouteImport.update({
    id: '/interview-analysis/$interviewId',
    path: '/interview-analysis/$interviewId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MockInterviewTranscriptInterviewIdRoute =
  MockInterviewTranscriptInterviewIdRouteImport.update({
    id: '/mock-interview-transcript/$interviewId',
    path: '/mock-interview-transcript/$interviewId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentActivityStudentIdRoute =
  StudentActivityStudentIdRouteImport.update({
    id: '/student-activity/$studentId',
    path: '/student-activity/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentDataStudentIdRoute = StudentDataStudentIdRouteImport.update({
  id: '/student-data/$studentId',
  path: '/student-data/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDetailStudentIdRoute = StudentDetailStudentIdRouteImport.update({
  id: '/student-detail/$studentId',
  path: '/student-detail/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentInterviewEvidenceStudentIdInterviewIdRoute =
  StudentInterviewEvidenceStudentIdInterviewIdRouteImport.update({
    id: '/student-interview-evidence/$studentId/$interviewId',
    path: '/student-interview-evidence/$studentId/$interviewId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentModuleStudentIdModuleKeyRoute =
  StudentModuleStudentIdModuleKeyRouteImport.update({
    id: '/student-module/$studentId/$moduleKey',
    path: '/student-module/$studentId/$moduleKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aplr-training': typeof AplrTrainingRoute
  '/basic-math-training': typeof BasicMathTrainingRoute
  '/candidate-auth': typeof CandidateAuthRoute
  '/candidate-profile': typeof CandidateProfileRoute
  '/chat': typeof ChatRoute
  '/client-chat': typeof ClientChatRoute
  '/client-onboarding': typeof ClientOnboardingRoute
  '/client-profile': typeof ClientProfileRoute
  '/communication-training': typeof CommunicationTrainingRoute
  '/communication-training-history': typeof CommunicationTrainingHistoryRoute
  '/communication-training-tips': typeof CommunicationTrainingTipsRoute
  '/companies': typeof CompaniesRoute
  '/company-drives': typeof CompanyDrivesRoute
  '/courses': typeof CoursesRoute
  '/daily-targets': typeof DailyTargetsRoute
  '/dashboard': typeof DashboardRoute
  '/drives': typeof DrivesRoute
  '/dsa-training': typeof DsaTrainingRoute
  '/english-training': typeof EnglishTrainingRoute
  '/english-training-history': typeof EnglishTrainingHistoryRoute
  '/english-training-tips': typeof EnglishTrainingTipsRoute
  '/gd-history': typeof GdHistoryRoute
  '/gd-room': typeof GdRoomRoute
  '/gd-training': typeof GdTrainingRoute
  '/get-started': typeof GetStartedRoute
  '/institute-billing': typeof InstituteBillingRoute
  '/institution-auth': typeof InstitutionAuthRoute
  '/ld-training': typeof LdTrainingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learning': typeof LearningRoute
  '/logout': typeof LogoutRoute
  '/mock-interview': typeof MockInterviewRoute
  '/mock-interview-history': typeof MockInterviewHistoryRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/placement-cell': typeof PlacementCellRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reports': typeof ReportsRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/roadmap-drill': typeof RoadmapDrillRoute
  '/sandbox': typeof SandboxRoute
  '/self-training': typeof SelfTrainingRoute
  '/situational-training': typeof SituationalTrainingRoute
  '/student-message': typeof StudentMessageRoute
  '/students': typeof StudentsRoute
  '/tac': typeof TacRoute
  '/technical-training': typeof TechnicalTrainingRoute
  '/tutorials': typeof TutorialsRoute
  '/communication-training-report/$sessionId': typeof CommunicationTrainingReportSessionIdRoute
  '/company-drives/$companyId': typeof CompanyDrivesCompanyIdRoute
  '/english-training-report/$sessionId': typeof EnglishTrainingReportSessionIdRoute
  '/gd-report/$gdId': typeof GdReportGdIdRoute
  '/interview-analysis/$interviewId': typeof InterviewAnalysisInterviewIdRoute
  '/mock-interview-transcript/$interviewId': typeof MockInterviewTranscriptInterviewIdRoute
  '/student-activity/$studentId': typeof StudentActivityStudentIdRoute
  '/student-data/$studentId': typeof StudentDataStudentIdRoute
  '/student-detail/$studentId': typeof StudentDetailStudentIdRoute
  '/student-interview-evidence/$studentId/$interviewId': typeof StudentInterviewEvidenceStudentIdInterviewIdRoute
  '/student-module/$studentId/$moduleKey': typeof StudentModuleStudentIdModuleKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aplr-training': typeof AplrTrainingRoute
  '/basic-math-training': typeof BasicMathTrainingRoute
  '/candidate-auth': typeof CandidateAuthRoute
  '/candidate-profile': typeof CandidateProfileRoute
  '/chat': typeof ChatRoute
  '/client-chat': typeof ClientChatRoute
  '/client-onboarding': typeof ClientOnboardingRoute
  '/client-profile': typeof ClientProfileRoute
  '/communication-training': typeof CommunicationTrainingRoute
  '/communication-training-history': typeof CommunicationTrainingHistoryRoute
  '/communication-training-tips': typeof CommunicationTrainingTipsRoute
  '/companies': typeof CompaniesRoute
  '/company-drives': typeof CompanyDrivesRoute
  '/courses': typeof CoursesRoute
  '/daily-targets': typeof DailyTargetsRoute
  '/dashboard': typeof DashboardRoute
  '/drives': typeof DrivesRoute
  '/dsa-training': typeof DsaTrainingRoute
  '/english-training': typeof EnglishTrainingRoute
  '/english-training-history': typeof EnglishTrainingHistoryRoute
  '/english-training-tips': typeof EnglishTrainingTipsRoute
  '/gd-history': typeof GdHistoryRoute
  '/gd-room': typeof GdRoomRoute
  '/gd-training': typeof GdTrainingRoute
  '/get-started': typeof GetStartedRoute
  '/institute-billing': typeof InstituteBillingRoute
  '/institution-auth': typeof InstitutionAuthRoute
  '/ld-training': typeof LdTrainingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learning': typeof LearningRoute
  '/logout': typeof LogoutRoute
  '/mock-interview': typeof MockInterviewRoute
  '/mock-interview-history': typeof MockInterviewHistoryRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/placement-cell': typeof PlacementCellRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reports': typeof ReportsRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/roadmap-drill': typeof RoadmapDrillRoute
  '/sandbox': typeof SandboxRoute
  '/self-training': typeof SelfTrainingRoute
  '/situational-training': typeof SituationalTrainingRoute
  '/student-message': typeof StudentMessageRoute
  '/students': typeof StudentsRoute
  '/tac': typeof TacRoute
  '/technical-training': typeof TechnicalTrainingRoute
  '/tutorials': typeof TutorialsRoute
  '/communication-training-report/$sessionId': typeof CommunicationTrainingReportSessionIdRoute
  '/company-drives/$companyId': typeof CompanyDrivesCompanyIdRoute
  '/english-training-report/$sessionId': typeof EnglishTrainingReportSessionIdRoute
  '/gd-report/$gdId': typeof GdReportGdIdRoute
  '/interview-analysis/$interviewId': typeof InterviewAnalysisInterviewIdRoute
  '/mock-interview-transcript/$interviewId': typeof MockInterviewTranscriptInterviewIdRoute
  '/student-activity/$studentId': typeof StudentActivityStudentIdRoute
  '/student-data/$studentId': typeof StudentDataStudentIdRoute
  '/student-detail/$studentId': typeof StudentDetailStudentIdRoute
  '/student-interview-evidence/$studentId/$interviewId': typeof StudentInterviewEvidenceStudentIdInterviewIdRoute
  '/student-module/$studentId/$moduleKey': typeof StudentModuleStudentIdModuleKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aplr-training': typeof AplrTrainingRoute
  '/basic-math-training': typeof BasicMathTrainingRoute
  '/candidate-auth': typeof CandidateAuthRoute
  '/candidate-profile': typeof CandidateProfileRoute
  '/chat': typeof ChatRoute
  '/client-chat': typeof ClientChatRoute
  '/client-onboarding': typeof ClientOnboardingRoute
  '/client-profile': typeof ClientProfileRoute
  '/communication-training': typeof CommunicationTrainingRoute
  '/communication-training-history': typeof CommunicationTrainingHistoryRoute
  '/communication-training-tips': typeof CommunicationTrainingTipsRoute
  '/companies': typeof CompaniesRoute
  '/company-drives': typeof CompanyDrivesRoute
  '/courses': typeof CoursesRoute
  '/daily-targets': typeof DailyTargetsRoute
  '/dashboard': typeof DashboardRoute
  '/drives': typeof DrivesRoute
  '/dsa-training': typeof DsaTrainingRoute
  '/english-training': typeof EnglishTrainingRoute
  '/english-training-history': typeof EnglishTrainingHistoryRoute
  '/english-training-tips': typeof EnglishTrainingTipsRoute
  '/gd-history': typeof GdHistoryRoute
  '/gd-room': typeof GdRoomRoute
  '/gd-training': typeof GdTrainingRoute
  '/get-started': typeof GetStartedRoute
  '/institute-billing': typeof InstituteBillingRoute
  '/institution-auth': typeof InstitutionAuthRoute
  '/ld-training': typeof LdTrainingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learning': typeof LearningRoute
  '/logout': typeof LogoutRoute
  '/mock-interview': typeof MockInterviewRoute
  '/mock-interview-history': typeof MockInterviewHistoryRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/placement-cell': typeof PlacementCellRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reports': typeof ReportsRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/roadmap-drill': typeof RoadmapDrillRoute
  '/sandbox': typeof SandboxRoute
  '/self-training': typeof SelfTrainingRoute
  '/situational-training': typeof SituationalTrainingRoute
  '/student-message': typeof StudentMessageRoute
  '/students': typeof StudentsRoute
  '/tac': typeof TacRoute
  '/technical-training': typeof TechnicalTrainingRoute
  '/tutorials': typeof TutorialsRoute
  '/communication-training-report/$sessionId': typeof CommunicationTrainingReportSessionIdRoute
  '/company-drives_/$companyId': typeof CompanyDrivesCompanyIdRoute
  '/english-training-report/$sessionId': typeof EnglishTrainingReportSessionIdRoute
  '/gd-report/$gdId': typeof GdReportGdIdRoute
  '/interview-analysis/$interviewId': typeof InterviewAnalysisInterviewIdRoute
  '/mock-interview-transcript/$interviewId': typeof MockInterviewTranscriptInterviewIdRoute
  '/student-activity/$studentId': typeof StudentActivityStudentIdRoute
  '/student-data/$studentId': typeof StudentDataStudentIdRoute
  '/student-detail/$studentId': typeof StudentDetailStudentIdRoute
  '/student-interview-evidence/$studentId/$interviewId': typeof StudentInterviewEvidenceStudentIdInterviewIdRoute
  '/student-module/$studentId/$moduleKey': typeof StudentModuleStudentIdModuleKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aplr-training'
    | '/basic-math-training'
    | '/candidate-auth'
    | '/candidate-profile'
    | '/chat'
    | '/client-chat'
    | '/client-onboarding'
    | '/client-profile'
    | '/communication-training'
    | '/communication-training-history'
    | '/communication-training-tips'
    | '/companies'
    | '/company-drives'
    | '/courses'
    | '/daily-targets'
    | '/dashboard'
    | '/drives'
    | '/dsa-training'
    | '/english-training'
    | '/english-training-history'
    | '/english-training-tips'
    | '/gd-history'
    | '/gd-room'
    | '/gd-training'
    | '/get-started'
    | '/institute-billing'
    | '/institution-auth'
    | '/ld-training'
    | '/leaderboard'
    | '/learning'
    | '/logout'
    | '/mock-interview'
    | '/mock-interview-history'
    | '/notifications'
    | '/onboarding'
    | '/placement-cell'
    | '/privacy-policy'
    | '/reports'
    | '/resume-builder'
    | '/roadmap-drill'
    | '/sandbox'
    | '/self-training'
    | '/situational-training'
    | '/student-message'
    | '/students'
    | '/tac'
    | '/technical-training'
    | '/tutorials'
    | '/communication-training-report/$sessionId'
    | '/company-drives/$companyId'
    | '/english-training-report/$sessionId'
    | '/gd-report/$gdId'
    | '/interview-analysis/$interviewId'
    | '/mock-interview-transcript/$interviewId'
    | '/student-activity/$studentId'
    | '/student-data/$studentId'
    | '/student-detail/$studentId'
    | '/student-interview-evidence/$studentId/$interviewId'
    | '/student-module/$studentId/$moduleKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aplr-training'
    | '/basic-math-training'
    | '/candidate-auth'
    | '/candidate-profile'
    | '/chat'
    | '/client-chat'
    | '/client-onboarding'
    | '/client-profile'
    | '/communication-training'
    | '/communication-training-history'
    | '/communication-training-tips'
    | '/companies'
    | '/company-drives'
    | '/courses'
    | '/daily-targets'
    | '/dashboard'
    | '/drives'
    | '/dsa-training'
    | '/english-training'
    | '/english-training-history'
    | '/english-training-tips'
    | '/gd-history'
    | '/gd-room'
    | '/gd-training'
    | '/get-started'
    | '/institute-billing'
    | '/institution-auth'
    | '/ld-training'
    | '/leaderboard'
    | '/learning'
    | '/logout'
    | '/mock-interview'
    | '/mock-interview-history'
    | '/notifications'
    | '/onboarding'
    | '/placement-cell'
    | '/privacy-policy'
    | '/reports'
    | '/resume-builder'
    | '/roadmap-drill'
    | '/sandbox'
    | '/self-training'
    | '/situational-training'
    | '/student-message'
    | '/students'
    | '/tac'
    | '/technical-training'
    | '/tutorials'
    | '/communication-training-report/$sessionId'
    | '/company-drives/$companyId'
    | '/english-training-report/$sessionId'
    | '/gd-report/$gdId'
    | '/interview-analysis/$interviewId'
    | '/mock-interview-transcript/$interviewId'
    | '/student-activity/$studentId'
    | '/student-data/$studentId'
    | '/student-detail/$studentId'
    | '/student-interview-evidence/$studentId/$interviewId'
    | '/student-module/$studentId/$moduleKey'
  id:
    | '__root__'
    | '/'
    | '/aplr-training'
    | '/basic-math-training'
    | '/candidate-auth'
    | '/candidate-profile'
    | '/chat'
    | '/client-chat'
    | '/client-onboarding'
    | '/client-profile'
    | '/communication-training'
    | '/communication-training-history'
    | '/communication-training-tips'
    | '/companies'
    | '/company-drives'
    | '/courses'
    | '/daily-targets'
    | '/dashboard'
    | '/drives'
    | '/dsa-training'
    | '/english-training'
    | '/english-training-history'
    | '/english-training-tips'
    | '/gd-history'
    | '/gd-room'
    | '/gd-training'
    | '/get-started'
    | '/institute-billing'
    | '/institution-auth'
    | '/ld-training'
    | '/leaderboard'
    | '/learning'
    | '/logout'
    | '/mock-interview'
    | '/mock-interview-history'
    | '/notifications'
    | '/onboarding'
    | '/placement-cell'
    | '/privacy-policy'
    | '/reports'
    | '/resume-builder'
    | '/roadmap-drill'
    | '/sandbox'
    | '/self-training'
    | '/situational-training'
    | '/student-message'
    | '/students'
    | '/tac'
    | '/technical-training'
    | '/tutorials'
    | '/communication-training-report/$sessionId'
    | '/company-drives_/$companyId'
    | '/english-training-report/$sessionId'
    | '/gd-report/$gdId'
    | '/interview-analysis/$interviewId'
    | '/mock-interview-transcript/$interviewId'
    | '/student-activity/$studentId'
    | '/student-data/$studentId'
    | '/student-detail/$studentId'
    | '/student-interview-evidence/$studentId/$interviewId'
    | '/student-module/$studentId/$moduleKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AplrTrainingRoute: typeof AplrTrainingRoute
  BasicMathTrainingRoute: typeof BasicMathTrainingRoute
  CandidateAuthRoute: typeof CandidateAuthRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  ChatRoute: typeof ChatRoute
  ClientChatRoute: typeof ClientChatRoute
  ClientOnboardingRoute: typeof ClientOnboardingRoute
  ClientProfileRoute: typeof ClientProfileRoute
  CommunicationTrainingRoute: typeof CommunicationTrainingRoute
  CommunicationTrainingHistoryRoute: typeof CommunicationTrainingHistoryRoute
  CommunicationTrainingTipsRoute: typeof CommunicationTrainingTipsRoute
  CompaniesRoute: typeof CompaniesRoute
  CompanyDrivesRoute: typeof CompanyDrivesRoute
  CoursesRoute: typeof CoursesRoute
  DailyTargetsRoute: typeof DailyTargetsRoute
  DashboardRoute: typeof DashboardRoute
  DrivesRoute: typeof DrivesRoute
  DsaTrainingRoute: typeof DsaTrainingRoute
  EnglishTrainingRoute: typeof EnglishTrainingRoute
  EnglishTrainingHistoryRoute: typeof EnglishTrainingHistoryRoute
  EnglishTrainingTipsRoute: typeof EnglishTrainingTipsRoute
  GdHistoryRoute: typeof GdHistoryRoute
  GdRoomRoute: typeof GdRoomRoute
  GdTrainingRoute: typeof GdTrainingRoute
  GetStartedRoute: typeof GetStartedRoute
  InstituteBillingRoute: typeof InstituteBillingRoute
  InstitutionAuthRoute: typeof InstitutionAuthRoute
  LdTrainingRoute: typeof LdTrainingRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LearningRoute: typeof LearningRoute
  LogoutRoute: typeof LogoutRoute
  MockInterviewRoute: typeof MockInterviewRoute
  MockInterviewHistoryRoute: typeof MockInterviewHistoryRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PlacementCellRoute: typeof PlacementCellRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReportsRoute: typeof ReportsRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  RoadmapDrillRoute: typeof RoadmapDrillRoute
  SandboxRoute: typeof SandboxRoute
  SelfTrainingRoute: typeof SelfTrainingRoute
  SituationalTrainingRoute: typeof SituationalTrainingRoute
  StudentMessageRoute: typeof StudentMessageRoute
  StudentsRoute: typeof StudentsRoute
  TacRoute: typeof TacRoute
  TechnicalTrainingRoute: typeof TechnicalTrainingRoute
  TutorialsRoute: typeof TutorialsRoute
  CommunicationTrainingReportSessionIdRoute: typeof CommunicationTrainingReportSessionIdRoute
  CompanyDrivesCompanyIdRoute: typeof CompanyDrivesCompanyIdRoute
  EnglishTrainingReportSessionIdRoute: typeof EnglishTrainingReportSessionIdRoute
  GdReportGdIdRoute: typeof GdReportGdIdRoute
  InterviewAnalysisInterviewIdRoute: typeof InterviewAnalysisInterviewIdRoute
  MockInterviewTranscriptInterviewIdRoute: typeof MockInterviewTranscriptInterviewIdRoute
  StudentActivityStudentIdRoute: typeof StudentActivityStudentIdRoute
  StudentDataStudentIdRoute: typeof StudentDataStudentIdRoute
  StudentDetailStudentIdRoute: typeof StudentDetailStudentIdRoute
  StudentInterviewEvidenceStudentIdInterviewIdRoute: typeof StudentInterviewEvidenceStudentIdInterviewIdRoute
  StudentModuleStudentIdModuleKeyRoute: typeof StudentModuleStudentIdModuleKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplr-training': {
      id: '/aplr-training'
      path: '/aplr-training'
      fullPath: '/aplr-training'
      preLoaderRoute: typeof AplrTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-math-training': {
      id: '/basic-math-training'
      path: '/basic-math-training'
      fullPath: '/basic-math-training'
      preLoaderRoute: typeof BasicMathTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-auth': {
      id: '/candidate-auth'
      path: '/candidate-auth'
      fullPath: '/candidate-auth'
      preLoaderRoute: typeof CandidateAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-profile': {
      id: '/candidate-profile'
      path: '/candidate-profile'
      fullPath: '/candidate-profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-chat': {
      id: '/client-chat'
      path: '/client-chat'
      fullPath: '/client-chat'
      preLoaderRoute: typeof ClientChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-onboarding': {
      id: '/client-onboarding'
      path: '/client-onboarding'
      fullPath: '/client-onboarding'
      preLoaderRoute: typeof ClientOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-profile': {
      id: '/client-profile'
      path: '/client-profile'
      fullPath: '/client-profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-training': {
      id: '/communication-training'
      path: '/communication-training'
      fullPath: '/communication-training'
      preLoaderRoute: typeof CommunicationTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-training-history': {
      id: '/communication-training-history'
      path: '/communication-training-history'
      fullPath: '/communication-training-history'
      preLoaderRoute: typeof CommunicationTrainingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-training-tips': {
      id: '/communication-training-tips'
      path: '/communication-training-tips'
      fullPath: '/communication-training-tips'
      preLoaderRoute: typeof CommunicationTrainingTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-drives': {
      id: '/company-drives'
      path: '/company-drives'
      fullPath: '/company-drives'
      preLoaderRoute: typeof CompanyDrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-targets': {
      id: '/daily-targets'
      path: '/daily-targets'
      fullPath: '/daily-targets'
      preLoaderRoute: typeof DailyTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drives': {
      id: '/drives'
      path: '/drives'
      fullPath: '/drives'
      preLoaderRoute: typeof DrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa-training': {
      id: '/dsa-training'
      path: '/dsa-training'
      fullPath: '/dsa-training'
      preLoaderRoute: typeof DsaTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-training': {
      id: '/english-training'
      path: '/english-training'
      fullPath: '/english-training'
      preLoaderRoute: typeof EnglishTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-training-history': {
      id: '/english-training-history'
      path: '/english-training-history'
      fullPath: '/english-training-history'
      preLoaderRoute: typeof EnglishTrainingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-training-tips': {
      id: '/english-training-tips'
      path: '/english-training-tips'
      fullPath: '/english-training-tips'
      preLoaderRoute: typeof EnglishTrainingTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gd-history': {
      id: '/gd-history'
      path: '/gd-history'
      fullPath: '/gd-history'
      preLoaderRoute: typeof GdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gd-room': {
      id: '/gd-room'
      path: '/gd-room'
      fullPath: '/gd-room'
      preLoaderRoute: typeof GdRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gd-training': {
      id: '/gd-training'
      path: '/gd-training'
      fullPath: '/gd-training'
      preLoaderRoute: typeof GdTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute-billing': {
      id: '/institute-billing'
      path: '/institute-billing'
      fullPath: '/institute-billing'
      preLoaderRoute: typeof InstituteBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution-auth': {
      id: '/institution-auth'
      path: '/institution-auth'
      fullPath: '/institution-auth'
      preLoaderRoute: typeof InstitutionAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ld-training': {
      id: '/ld-training'
      path: '/ld-training'
      fullPath: '/ld-training'
      preLoaderRoute: typeof LdTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview': {
      id: '/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof MockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview-history': {
      id: '/mock-interview-history'
      path: '/mock-interview-history'
      fullPath: '/mock-interview-history'
      preLoaderRoute: typeof MockInterviewHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement-cell': {
      id: '/placement-cell'
      path: '/placement-cell'
      fullPath: '/placement-cell'
      preLoaderRoute: typeof PlacementCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap-drill': {
      id: '/roadmap-drill'
      path: '/roadmap-drill'
      fullPath: '/roadmap-drill'
      preLoaderRoute: typeof RoadmapDrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-training': {
      id: '/self-training'
      path: '/self-training'
      fullPath: '/self-training'
      preLoaderRoute: typeof SelfTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situational-training': {
      id: '/situational-training'
      path: '/situational-training'
      fullPath: '/situational-training'
      preLoaderRoute: typeof SituationalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-message': {
      id: '/student-message'
      path: '/student-message'
      fullPath: '/student-message'
      preLoaderRoute: typeof StudentMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tac': {
      id: '/tac'
      path: '/tac'
      fullPath: '/tac'
      preLoaderRoute: typeof TacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-training': {
      id: '/technical-training'
      path: '/technical-training'
      fullPath: '/technical-training'
      preLoaderRoute: typeof TechnicalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-training-report/$sessionId': {
      id: '/communication-training-report/$sessionId'
      path: '/communication-training-report/$sessionId'
      fullPath: '/communication-training-report/$sessionId'
      preLoaderRoute: typeof CommunicationTrainingReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-drives_/$companyId': {
      id: '/company-drives_/$companyId'
      path: '/company-drives/$companyId'
      fullPath: '/company-drives/$companyId'
      preLoaderRoute: typeof CompanyDrivesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-training-report/$sessionId': {
      id: '/english-training-report/$sessionId'
      path: '/english-training-report/$sessionId'
      fullPath: '/english-training-report/$sessionId'
      preLoaderRoute: typeof EnglishTrainingReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gd-report/$gdId': {
      id: '/gd-report/$gdId'
      path: '/gd-report/$gdId'
      fullPath: '/gd-report/$gdId'
      preLoaderRoute: typeof GdReportGdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-analysis/$interviewId': {
      id: '/interview-analysis/$interviewId'
      path: '/interview-analysis/$interviewId'
      fullPath: '/interview-analysis/$interviewId'
      preLoaderRoute: typeof InterviewAnalysisInterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview-transcript/$interviewId': {
      id: '/mock-interview-transcript/$interviewId'
      path: '/mock-interview-transcript/$interviewId'
      fullPath: '/mock-interview-transcript/$interviewId'
      preLoaderRoute: typeof MockInterviewTranscriptInterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-activity/$studentId': {
      id: '/student-activity/$studentId'
      path: '/student-activity/$studentId'
      fullPath: '/student-activity/$studentId'
      preLoaderRoute: typeof StudentActivityStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-data/$studentId': {
      id: '/student-data/$studentId'
      path: '/student-data/$studentId'
      fullPath: '/student-data/$studentId'
      preLoaderRoute: typeof StudentDataStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-detail/$studentId': {
      id: '/student-detail/$studentId'
      path: '/student-detail/$studentId'
      fullPath: '/student-detail/$studentId'
      preLoaderRoute: typeof StudentDetailStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-interview-evidence/$studentId/$interviewId': {
      id: '/student-interview-evidence/$studentId/$interviewId'
      path: '/student-interview-evidence/$studentId/$interviewId'
      fullPath: '/student-interview-evidence/$studentId/$interviewId'
      preLoaderRoute: typeof StudentInterviewEvidenceStudentIdInterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-module/$studentId/$moduleKey': {
      id: '/student-module/$studentId/$moduleKey'
      path: '/student-module/$studentId/$moduleKey'
      fullPath: '/student-module/$studentId/$moduleKey'
      preLoaderRoute: typeof StudentModuleStudentIdModuleKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AplrTrainingRoute: AplrTrainingRoute,
  BasicMathTrainingRoute: BasicMathTrainingRoute,
  CandidateAuthRoute: CandidateAuthRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  ChatRoute: ChatRoute,
  ClientChatRoute: ClientChatRoute,
  ClientOnboardingRoute: ClientOnboardingRoute,
  ClientProfileRoute: ClientProfileRoute,
  CommunicationTrainingRoute: CommunicationTrainingRoute,
  CommunicationTrainingHistoryRoute: CommunicationTrainingHistoryRoute,
  CommunicationTrainingTipsRoute: CommunicationTrainingTipsRoute,
  CompaniesRoute: CompaniesRoute,
  CompanyDrivesRoute: CompanyDrivesRoute,
  CoursesRoute: CoursesRoute,
  DailyTargetsRoute: DailyTargetsRoute,
  DashboardRoute: DashboardRoute,
  DrivesRoute: DrivesRoute,
  DsaTrainingRoute: DsaTrainingRoute,
  EnglishTrainingRoute: EnglishTrainingRoute,
  EnglishTrainingHistoryRoute: EnglishTrainingHistoryRoute,
  EnglishTrainingTipsRoute: EnglishTrainingTipsRoute,
  GdHistoryRoute: GdHistoryRoute,
  GdRoomRoute: GdRoomRoute,
  GdTrainingRoute: GdTrainingRoute,
  GetStartedRoute: GetStartedRoute,
  InstituteBillingRoute: InstituteBillingRoute,
  InstitutionAuthRoute: InstitutionAuthRoute,
  LdTrainingRoute: LdTrainingRoute,
  LeaderboardRoute: LeaderboardRoute,
  LearningRoute: LearningRoute,
  LogoutRoute: LogoutRoute,
  MockInterviewRoute: MockInterviewRoute,
  MockInterviewHistoryRoute: MockInterviewHistoryRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PlacementCellRoute: PlacementCellRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReportsRoute: ReportsRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  RoadmapDrillRoute: RoadmapDrillRoute,
  SandboxRoute: SandboxRoute,
  SelfTrainingRoute: SelfTrainingRoute,
  SituationalTrainingRoute: SituationalTrainingRoute,
  StudentMessageRoute: StudentMessageRoute,
  StudentsRoute: StudentsRoute,
  TacRoute: TacRoute,
  TechnicalTrainingRoute: TechnicalTrainingRoute,
  TutorialsRoute: TutorialsRoute,
  CommunicationTrainingReportSessionIdRoute:
    CommunicationTrainingReportSessionIdRoute,
  CompanyDrivesCompanyIdRoute: CompanyDrivesCompanyIdRoute,
  EnglishTrainingReportSessionIdRoute: EnglishTrainingReportSessionIdRoute,
  GdReportGdIdRoute: GdReportGdIdRoute,
  InterviewAnalysisInterviewIdRoute: InterviewAnalysisInterviewIdRoute,
  MockInterviewTranscriptInterviewIdRoute:
    MockInterviewTranscriptInterviewIdRoute,
  StudentActivityStudentIdRoute: StudentActivityStudentIdRoute,
  StudentDataStudentIdRoute: StudentDataStudentIdRoute,
  StudentDetailStudentIdRoute: StudentDetailStudentIdRoute,
  StudentInterviewEvidenceStudentIdInterviewIdRoute:
    StudentInterviewEvidenceStudentIdInterviewIdRoute,
  StudentModuleStudentIdModuleKeyRoute: StudentModuleStudentIdModuleKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
